"use client";
import { useRef, useState } from "react";
import { motion } from "framer-motion";
import Head from "next/head";
import TransitionEffect from "@/components/TransitionEffect";
import emailjs from "@emailjs/browser";

const Contact = () => {
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(false);
  const text = "Send Message";

  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();
    setError(false);
    setSuccess(false);

    emailjs
      .sendForm(
        process.env.NEXT_PUBLIC_SERVICE_ID,
        process.env.NEXT_PUBLIC_TEMPLATE_ID,
        form.current,
        process.env.NEXT_PUBLIC_PUBLIC_KEY
      )
      .then(
        () => {
          setSuccess(true);
          form.current.reset();
        },
        () => {
          setError(true);
        }
      );
  };

  return (
    <>
      <Head>
        <title>Maor_saadia/Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />

      <div className="h-full mb-16 flex flex-col lg:flex-row px-4 xs:px-4 sm:px-8 md:px-12 lg:px-20 xl:px-48">
        <div className="lg:w-1/2 flex items-center justify-center xs:text-2xl sm:text-4xl md:text-6xl lg:text-8xl text-slate-500">
          <div>
            {text.split("").map((letter, index) => (
              <motion.span
                key={index}
                initial={{ opacity: 1 }}
                animate={{ opacity: 0 }}
                transition={{
                  duration: 3,
                  repeat: Infinity,
                  delay: index * 0.1,
                }}
              >
                {letter}
              </motion.span>
            ))}
          </div>
        </div>
        <form
          onSubmit={sendEmail}
          ref={form}
          className="h-1/2 lg:h-full lg:w-1/2 bg-gradient-to-b from-slate-200 to-slate-500 dark:from-slate-500 dark:to-slate-800 dark:bg-slate-600 rounded-xl text-xl flex flex-col gap-8 justify-center p-24"
        >
          <span>Write Your Message Here,</span>
          <textarea
            rows={6}
            className="bg-transparent border-b-2 border-b-black outline-none resize-none"
            name="user_message"
          />
          <span>Mail Address:</span>
          <input
            name="user_email"
            type="text"
            className="bg-transparent border-b-2 border-b-black outline-none"
          />
          <span>Regards</span>
          <button className="bg-slate-200 dark:bg-slate-500 rounded font-semibold dark:text-light p-4">
            Send
          </button>
          {success && (
            <span className="text-green-600 font-semibold">
              Your message has been sent successfully!
            </span>
          )}
          {error && (
            <span className="text-red-400 dark:text-red-300 font-semibold">
              Something went wrong!
            </span>
          )}
        </form>
      </div>
    </>
  );
};

export default Contact;
