import Head from "next/head";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Maor_saadia/Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>contact</div>;
    </>
  );
};

export default Contact;
