"use client";

import Head from "next/head";

import RecentProjects from "../components/RecentProjects";
import Scroll from "../components/Scroll";
import TransitionEffect from "@/components/TransitionEffect";

const Projects = () => {
  return (
    <>
      <Head>
        <title>Maor_saadia/Projects</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-full justify-center">
        <div className="py-20">
          <div className="flex items-center justify-center xs:text-5xl sm:text-6xl md:text-7xl lg:text-8xl text-center dark:text-white">
            My Works
          </div>
          <TransitionEffect />

          <div className="flex gap-12 justify-center m-14">
            <Scroll />
          </div>
          <RecentProjects />
        </div>
      </div>
    </>
  );
};

export default Projects;
